version: '3.9'
services:
  stable-diffusion-server-queue-worker:
    container_name: stable-diffusion-server-queue-worker
    image: stable-diffusion-server-queue-worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      S3_ENDPOINT: http://localstack-s3-sqs:4566
      SQS_ENDPOINT: http://localstack-s3-sqs:4566
      STABLE_DIFFUSION_SERVICE_URL: https://big-blackberry-spinach.salad.cloud
      SALAD_API_KEY: ${SALAD_API_KEY}
      QUEUE_URL: http://localstack-s3-sqs:4566/000000000000/stable-diffusion-server-jobs.fifo
      JOB_TABLE: test-table
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      IMAGE_CACHE_BUCKET: dreamup-web-image-cache
      IMAGE_CACHE_TABLE: web-image-cache
      USER_CONTENT_BUCKET: dreamup-user-content
      PUBLIC_STATS_TABLE: public-stats
      IMAGE_COUNT_KEY: images_generated_count
      IMAGE_CACHE_QUEUE: web-image-caching-jobs.fifo
  localstack:
    container_name: "localstack-s3-sqs"
    image: localstack/localstack:2.0.1
    ports:
      - "4566:4566" # LocalStack Gateway
      # - "4571:4571" # external services port range
    environment:
      DEBUG: ${DEBUG-}
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: s3,sqs
      START_WEB: 0
      PROVIDER_OVERRIDE_S3: v2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal