#! /usr/bin/env bash

VERSION="$(cat package.json | jq -r '.version')-nitro-diffusion"
echo "Building version $VERSION"

docker buildx build \
--platform linux/amd64 \
-t public.ecr.aws/i0t3i1w9/stable-diffusion-service-queue-worker:$VERSION \
-f Dockerfile.x.nitro-diffusion \
.